# Dockerfile.frontend
# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install

# Copy the rest of the app code
COPY . .

# Build the React app for production
RUN npm run build

# Expose React port
EXPOSE 3000

# Run React app
CMD ["npm", "start"]

