
services:
  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - FLASK_ENV=development

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
